"""organizations + memberships

Revision ID: 0ab56cd8fc27
Revises: ab32f7ffdfd0
Create Date: 2026-09-10 06:22:10.299601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab56cd8fc27'
down_revision: Union[str, Sequence[str], None] = 'ab32f7ffdfd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_org_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_github_org_id'), ['github_org_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_login'), ['login'], unique=True)

    op.create_table('org_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_membership_user_org')
    )
    with op.batch_alter_table('org_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_memberships_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_memberships_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_org_memberships_org_id'))

    op.drop_table('org_memberships')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_login'))
        batch_op.drop_index(batch_op.f('ix_organizations_github_org_id'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
