"""project config_json + phase_runs

Revision ID: ab32f7ffdfd0
Revises: 5e68cc8e1ce6
Create Date: 2026-09-10 06:15:38.495399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab32f7ffdfd0'
down_revision: Union[str, Sequence[str], None] = '5e68cc8e1ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phase_key', sa.String(length=32), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phase_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phase_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phase_runs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_json', sa.Text(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('config_json')

    with op.batch_alter_table('phase_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phase_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_phase_runs_project_id'))

    op.drop_table('phase_runs')
    # ### end Alembic commands ###
